gcc -fPIC -DSOCKET_THREAD -I/mnt/net/netconfig/install/include -I/mnt/net/netconfig/ -I/mnt/net/netconfig/socket/ -I/mnt/net/netconfig/string/ -I/mnt/net/netconfig/thread_queue/ -I/mnt/net/netconfig/timer/ -L/mnt/net/netconfig/install -L/mnt/net/netconfig/install -lpthread -lrt -lcurl -o timer \
rbtree.c net_timer.c datelist.c
